# Este é um fluxo de trabalho básico para ajudar você a começar com GitHub Actions

name: CI

# Controla quando o fluxo de trabalho será executado
on:
  # Aciona o fluxo em push ou pull request no branch "main"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Permite executar manualmente na aba Actions
  workflow_dispatch:

jobs:
  # Um único job chamado "build"
  build:
    # O tipo de runner
    runs-on: ubuntu-latest

    steps:
      # Faz checkout do repositório
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Executa um comando simples
      - name: Executa um script de uma linha
        run: echo "Olá, mundo!"

      # Executa comandos múltiplos
      - name: Executa um script multi-linha
        run: |
          echo "Adicionar outras ações para build,"
          echo "testar e implantar seu projeto."
